### ISSUE TITLE
make error: mgAudioAL.cpp needs AL/alc.h

### ISSUE THREAD

**Issue by 0joshuaolson1** [mgoodfel/SeaOfMemes#1]
On Linux Mint 17/Qiana before and after apt-getting the libs in the readme:

../Source/Audio/mgAudioAL.cpp:41:20: fatal error: AL/alc.h: No such file or directory
 #include "AL/alc.h"
                    ^
compilation terminated.
make[1]: **\* [Debug/Audio/mgAudioAL.o] Error 1
make[1]: Leaving directory `/home/zenox/SeaOfMemes-master/Milligram/mgUtil/BuildLinux'
make: **\* [mgUtil] Error 2

**Comment by mgoodfel** [comment]
Yes, I don't think I listed absolutely everything you need.  Try finding 
something like libopenal1-dev, although I'm not sure exactly what it's 
called.

Michael.

**Comment by 0joshuaolson1** [comment]
Awesome. What I needed was libopenal-dev (no 1). Now I get a GLXBadFBConfig error, so I guess I need to use a computer with something better than OpenGL 2.1.

**Comment by mgoodfel** [comment]
I wish the list were more complete, but the only way to do it right is 
start with a clean linux install, and write down all the packages I 
need.  When you've been doing development on a machine, you already have 
all kinds of stuff.

Let me know if you have any other problems.

Michael.

**Comment by 0joshuaolson1** [comment]
On my Mac now with 10.10 Yosemite and OpenGL 3.1:

=== BUILD TARGET mgSendLog OF PROJECT mgSendLog WITH CONFIGURATION Release ===

Check dependencies
error: There is no SDK with the name or path '/Users/zenox/SeaOfMemes-master/Milligram/mgSendLog/BuildOSX/macosx10.7'

*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
make: **\* [mgSendLog] Error 65

Thanks for helping! I really want to check this out before I move to blackvoxel.

**Comment by mgoodfel** [comment]
Ah, the Mac.  Definitely the most difficult of the three development 
environments!

Open the project with XCode.  It's in Milligram/mgSendLog/BuildOSX.

I don't have my Mac running at the moment, so I can't tell you exactly 
where the field is, but somewhere in the build target page, there's a 
target OS version.  Just change that to whatever you are running now, 
and build it.

Michael.

**Comment by 0joshuaolson1** [comment]
Lol, that was all I needed! Now it runs, albeit slowly and with lots of rainbow glitch polygons. I didn't get the chance to make a screenshot, but this is a different issue and I think we can close this one now. :)

**Comment by mgoodfel** [comment]
Yes, please send a screenshot.  What hardware are you running on?  It 
runs on my 2012 Macbook Air.

Michael.

**Comment by 0joshuaolson1** [comment]
Watch for a newly opened issue for that one.
